- import_tasks: build_provider.yaml
  tags:
    - checkAS3URI

- import_tasks: populate_status.yaml
  tags:
    - checkAS3URI

- import_tasks: bigip_wait.yaml
  tags:
    - checkAS3URI

- import_tasks: checkAS3URI.yaml
  when: active_host == True
  tags:
    - checkAS3URI
