"app3": {
    "class": "Application",
    "template": "http",
    "serviceMain": {
        "class": "Service_HTTP",
        "virtualAddresses": [
            "10.30.10.7"
        ],
        "pool": "app3_pool"
    },
    "app3_pool": {
        "class": "Pool",
        "monitors": [
            "http"
        ],
        "members": [
            {
                "servicePort": 8001,
                "serverAddresses": [
                    "20.30.11.1", "20.30.11.2"
                ]
            }
        ]
    }
}
,
"app4": {
    "class": "Application",
    "template": "http",
    "serviceMain": {
        "class": "Service_HTTP",
        "virtualAddresses": [
            "10.40.10.1"
        ],
        "pool": "app4_pool"
    },
    "app4_pool": {
        "class": "Pool",
        "monitors": [
            "http"
        ],
        "members": [
            {
                "servicePort": 8001,
                "serverAddresses": [
                    "20.40.11.1", "20.40.11.2"
                ]
            }
        ]
    }
}
