---
- name: Build apps
  hosts: "{{bigip1_hostname}}_{{bigip2_hostname}}_{{ version }}"
  # hosts: onboarded-ha-pair
  connection: local
  gather_facts: yes

  roles:
    - manage-secret
    - appBuilds
