---

- name: Get IP addresses from IPAM, add hosts to Tower, push to repo
  hosts: ipam
  connection: local
  gather_facts: yes

  
  roles:
    - manage-secret
    - getIPsAllBigips
    - buildHostsOnTower

